name: otter-store
version: 1.1.0
summary: Otter Store
description: App store

confinement: strict
base: core18
grade: stable

apps:
  otter-store:
    command: desktop-launch otter_store
    extensions: [flutter-dev] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    - desktop
    - home

parts:
  otter-store:
    source: https://github.com/pedroermarinho/otter_store.git
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application 
