name: otter-store
version: 1.1.0
summary: Otter Store
description: App store

confinement: strict
base: core18
grade: stable
icon: snap/gui/otter-store.png

apps:
  otter-store:
    command: desktop-launch otter_store
    extensions: [flutter-master]
    plugs:
    - network
    - desktop
    - home

parts:
  otter-store:
    source: https://github.com/pedroermarinho/otter_store.git
    plugin: flutter
    flutter-target: lib/main.dart
